insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lobster - Base', 15.12);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Russian Prince', 71.81);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cake Slab', 47.35);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Whmis Spray Bottle Graduated', 23.61);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beer - Original Organic Lager', 17.01);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Creme De Banane - Marie', 37.84);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Chardonnay South', 43.92);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Tuna - Loin', 11.05);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Filling - Mince Meat', 70.09);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Onions - Spanish', 58.92);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ecolab Silver Fusion', 83.44);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Longos - Chicken Wings', 8.08);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Coffee - Almond Amaretto', 13.25);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Charddonnay Errazuriz', 61.32);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bar Nature Valley', 72.1);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Barbera Alba Doc 2001', 12.19);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pastry - Baked Scones - Mini', 84.51);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beef - Sushi Flat Iron Steak', 66.41);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cheese - Grana Padano', 62.33);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Aromat Spice / Seasoning', 48.53);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Garlic - Elephant', 77.22);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Skewers - Bamboo', 73.76);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Monkfish - Fresh', 81.36);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Magnotta - Bel Paese White', 93.66);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Appetizer - Sausage Rolls', 13.53);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pail For Lid 1537', 6.05);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ecolab - Ster Bac', 79.09);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Shrimp - Black Tiger 8 - 12', 96.93);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Extract - Raspberry', 84.02);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lemonade - Black Cherry, 591 Ml', 27.7);